name: Creepers Gonna Creep
main: me.spike.creeperprank.CreeperPrank
version: 1.0
author: SpikeMeister
description: >
             Creepers Gonna Creep lets ops prank their users by making them spawn creepers occasionally when they move.
commands:
  creeperprank:
    description: Adds a player to the list of prankees Probability optional. Default probability is 0.005.
    usage: |
           /<command> [player name] [probability]
           Example: /<command> name 0.1 - Adds "name" to the list of players to be pranked with probability 0.1.
           Example: /<command> name - Adds "name" to the list of players to be pranked with probability 0.005.
  setspawnprob:
    description: Sets the probability that player will spawn a creeper.
    usage: |
           /<command> [player name] [probability]
           Example: /<command> name 0.01 - Sets the probability of "name" spawning a creeper to 1 in 100.
  stoppranking:
    description: Sets the probability of a player spawning a creeper to 0.
    usage: |
           /<command> [player name]
           Example: /<command> name
  beingpranked:
    description: Checks if a player is being pranked and returns the probability they will spawn a creeper.
    usage: |
           /<command> [player name]
           Example: /<command> name
           